version: "3.7"

services:
  postgres_cadastro:
    container_name: ordem_servico
    image: postgres:12.2
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
